spring:
  application:
    name: 'clinica-alura'
  datasource:
    url: 'jdbc:postgresql://localhost:5432/clinica_alura'
    username: 'root'
    password: 'root'
  jpa:
    hibernate:
      ddl-auto: 'none'
    show-sql: true
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.PostgreSQLDialect'