-- 1. Eliminar la restricción actual de la llave primaria
ALTER TABLE medicos DROP CONSTRAINT medicos_pkey;

-- 2. Cambiar la columna id a BIGSERIAL
ALTER TABLE medicos ALTER COLUMN id TYPE BIGINT;
ALTER TABLE medicos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- 3. Volver a agregar la restricción de la llave primaria
ALTER TABLE medicos ADD PRIMARY KEY (id);
